# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67577edd9d43391c97e323b5496e1187a86d35a32cb813786fec90b7628b71da5ad77c9308686518c3158c146defa98326cdc28b75d70dab1c7f90c4bba12d96

test:
  secret_key_base: b8aa9abc8e2352a6ca2a675705038120e1be19c41721c496ab0d154abf9c326aeb7f5822dddc9a53cd76d7bb47047422e3cb8d9ab9c7b46b4d90becff32ae4bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
